"""page - recognized text

Revision ID: 3714db49fd63
Revises: 97cae2496046
Create Date: 2024-07-09 17:17:38.844993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3714db49fd63'
down_revision: Union[str, None] = '97cae2496046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('recognized_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'recognized_text')
    # ### end Alembic commands ###
