"""Add processed_text to pages

Revision ID: 3f02ce318e8b
Revises: d881588f8a9c
Create Date: 2024-07-21 13:47:18.407030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f02ce318e8b'
down_revision: Union[str, None] = 'd881588f8a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('processed_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'processed_text')
    # ### end Alembic commands ###
