"""creator for documents

Revision ID: f78d234925cf
Revises: dc8890adbfa0
Create Date: 2024-07-07 05:48:02.438325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78d234925cf'
down_revision: Union[str, None] = 'dc8890adbfa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'documents', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'created_by')
    # ### end Alembic commands ###
